description: default config

# Data related configs
data :
  type      : synthetic
  name      : gaussian-2d
  version   : v1
  size      : 200
  dimension : 2
  rho       : 0.5
  sample_run: false
  sample_num: 500
  preprocess: False

# training related
training :
  batch_size : 64
  num_epochs : 1000

# system
system:
  num_workers : 10
  use_cuda    : true
  seed        : 0

# model related configs
model:
  use_dropout : [True, True, False]
  drop_prob   : [0.5, 0.5, 0.5]
  use_ac_func : [True, True, False]
  activation  : 'relu'
  last_layer_activation: null
  latent_dim  : 10
  n_critic    : 2

  generator_hidden_layers : [16, 32]
  disc_hidden_layers      : [32, 16]

# hyperameters
hyperparams:
  g_lr         : 0.001
  d_lr         : 0.001
  g_betas      : [0.5, 0.9]
  d_betas      : [0.5, 0.9]
  weight_decay : 0.0001
  gamma        : 10
