description: default config

# Data related configs
data :
  type      : synthetic
  name      : dataset_1
  sample_run: false
  sample_num: 500
  preprocess: False
  version   : 1

# training related
training :
  batch_size : 128
  num_epochs : 5

# system
system:
  num_workers : 10
  use_cuda    : false
  seed        : 0

# model related configs
model:
  num_channels_first    : 64
  num_channels_prefinal : 64
  noise_dim             : 10
  n_critic              : 1
  num_layers            : 4

  use_init              : True
  use_batch_norm        : True

  generator_hidden_layers : [16, 32]
  disc_hidden_layers      : [32, 16]

# hyperameters
hyperparams:
  g_lr         : 0.0001
  d_lr         : 0.0001
  g_betas      : [0.5, 0.9]
  d_betas      : [0.5, 0.9]
  g_weight_decay : 0.0001
  d_weight_decay : 0.0001